# Generated by Django 6.0.2 on 2026-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_lat',
            field=models.FloatField(default=22.747275),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_lon',
            field=models.FloatField(default=75.895755),
        ),
    ]
