# Generated by Django 6.0.2 on 2026-02-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentprofile_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
