# Generated by Django 6.0.2 on 2026-04-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_course_studentprofile_course_year_semester_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='year',
            name='course',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
