# Generated by Django 6.0.2 on 2026-04-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_course_year_semester_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquery',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
