# Generated by Django 6.0.2 on 2026-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_studentprofile_course_studentprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquery',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
