# Generated by Django 6.0.2 on 2026-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_studentquery_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
