# Generated by Django 6.0.2 on 2026-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
